name: Graphs

on:
  push:
    branches: [ "main", "dev/**" ]

env:
  BUILD_TYPE: Debug

jobs:

  build-project:

    runs-on: ubuntu-latest
    container: morapresence/mond_db_debug

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{ github.workflow }}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{ github.workflow }}/build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workflow }}/build/**/*

  tests:
    needs: [ build-project ]

    runs-on: ubuntu-latest
    container: morapresence/mond_db_debug

    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workflow }}/build

      - name: Move to workspace
        run: |
          mkdir -p ${{ github.workspace }}/build
          mv ${{ github.workflow }}/build/* ${{ github.workspace }}/build

      - name: Test
        run: |
          cd ${{ github.workspace }}/build/Tests/
          chmod 777 Graphs_tests
          ./Graphs_tests
  

  valgrind:
    needs: [ build-project ]

    runs-on: ubuntu-latest
    container: morapresence/mond_db_tests

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workflow }}/build

      - name: Move to workspace
        run: |
          mkdir -p ${{ github.workspace }}/build
          mv ${{ github.workflow }}/build/* ${{ github.workspace }}/build

      - name: valgrind
        run: |
          chmod 777 ${{github.workspace}}/build/Tests/Graphs_tests
          valgrind --tool=memcheck --leak-check=yes ${{github.workspace}}/build/Tests/Graphs_tests
